import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <Link href="/quickstart">
            <h2>
              QuickStart <span>-&gt;</span>
            </h2>
            <p style={{ marginTop: 4 }}>コンポーネントの作成とネスト</p>
          </Link>

          <Link href="/quickstart/data">
            <h2>
              QuickStart <span>-&gt;</span>
            </h2>
            <p style={{ marginTop: 4 }}>データの表示</p>
          </Link>
        </div>
      </main>
    </>
  );
}
